'use strict';
// Bundles views/**/*.ejs into lib/views.generated.js so the pages render on serverless hosts.
const fs = require('fs');
const path = require('path');
const { readDir, viewsDir } = require('../lib/views');

const map = readDir(viewsDir);
const keys = Object.keys(map).sort();
const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])}`).join(',\n');
const out = `'use strict';\n// GENERATED by scripts/build-views.js from views/**/*.ejs. Do not edit by hand.\nmodule.exports = {\n${body}\n};\n`;
fs.writeFileSync(path.join(__dirname, '..', 'lib', 'views.generated.js'), out);
console.log(`Bundled ${keys.length} views into lib/views.generated.js`);
